### ISSUE TITLE
CMAKE_GENERATOR other than make doesn't work

### ISSUE THREAD

**Issue by 0xDEAD** [welovemaps/zserio#10]
If you set CMAKE_GENERATOR to something different than make, you would also need to overwrite MAKE (which is actually the binary that is called for compilation).  If you don't do this, the build will fail.

I would expect a warning (at least!) in this case, better let cmake handle that for you. Calling cmake with the option `--build <dir>` will find out the binary and call it.

To reproduce this issue on linux install [ninja](https://ninja-build.org/) and run:
```
CMAKE_GENERATOR=Ninja ./scripts/build.sh all-linux64
```

**Comment by Mi-La** [comment]
Fixed by d7d0b12d7e36ed16390f8e699d1c9d10367ea0ce
