### ISSUE TITLE
Add new language element for variable integers

### ISSUE THREAD

**Issue by fklebert** [welovemaps/zserio#2]
Currently zserio supports variable integer encoding with fixed sizes of the resulting bytes.
So a varuint64 in zserio cannot really hold the complete range of 64 bit but has a payload of 57 bit. The other bits are used for the variable encoding.
Other serialization languages do feature complete range with variable encoding. This can result in byte sizes greater than 8 bytes for varuint64 for example.

We should also add this capability to zserio so that we can retrofit it onto other serializations as well.

Proposal is to have:

type | payload | comment
----|-----|------
varuint | up to 64 bit | 
varint | up to 64 bit |
var(u)int64 | up to 57 bit | keep  for backward compatibility
var(u)int32 | up to 29 bit | keep for backward compatibility
var(u)int16| up to 15 bit | keep for backward compatibility

Keeping the current variable integer encodings may also be useful for people who rather want to stick with the sizes rather than total variable encoding.

**Comment by Mi-La** [comment]
Resolved by e12443692b722d4c873e0aea2027d07527b8784e
