### ISSUE TITLE
EndOfFile-token is called 'null' by parser

### ISSUE THREAD

**Issue by 0xDEAD** [welovemaps/zserio#5]
If a token is missing at the end of a parsed zserio-file, 'null' is reported to be found.
Could we rename this token of EndOfFile, that would make it easier to undersstand what is missing.

```
Parsing test.ds
[ERROR] test.ds:2:1: expecting SEMICOLON, found 'null'

```

**Comment by Mi-La** [comment]
Fixed by 9cd21d3.
