### ISSUE TITLE
Add possibility to build out-of-source

### ISSUE THREAD

**Issue by 0xDEAD** [welovemaps/zserio#7]
scripts/build.sh always builds into the fixed directories <projectroot>/build and deploys into <projectroot>/distr. That will not work on read-only source checkouts.

Please add an option to specify a build-directory, creating the subdirectories build / distr inside the specified directory is *imho* fine.

**Comment by Mi-La** [comment]
What means read-only source checkout? Do you mean that the checked out folder is read only? Could you please specify the use case?

**Comment by Mi-La** [comment]
Implemented in df974b15c653555e666ece869c250b4946d8d596
